version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: my-redis
    ports:
      - "6379:6379"  # 호스트:컨테이너
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis_data:/data # 데이터 보존을 위한 볼륨 마운트
      # [추가] 내 컴퓨터의 redis.conf를 컨테이너 내부로 연결
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    restart: always

  postgres:
    image: postgres:15-alpine
    container_name: my-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: wisenut       # .env 변수 사용 권장
      POSTGRES_PASSWORD: wisenut1!
      POSTGRES_DB: data_info
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    restart: always

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    runtime: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: all
    shm_size: "2gb"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: my-frontend:latest
    container_name: frontend
    ports:
      - "3000:80"
    restart: always

  mcp-server:
    build: 
      context: ./mcp-server
      dockerfile: Dockerfile
    image: my-mcp-server:latest
    container_name: mcp-server
    ports:
      - "9090:9090"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres
    restart: always

  gateway:
    build: 
      context: ./gateway
      dockerfile: Dockerfile
    image: my-gateway:latest
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - frontend
    restart: always

  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    image: my-agent:latest
    container_name: agent
    ports:
      - "8000:8000"
    env_file:
    - ./agent/.env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_PASSWORD: wisenut1!
      LLM_MODEL: llama3.1:8b
      MCP_SERVER_URL: http://mcp-server:9090
      OLLAMA_BASE_URL: http://ollama:11434
    depends_on:
      - redis
      - gateway

volumes:
  ollama_data: