spring:
  application:
    name: gateway
  data:
    redis:
      host: localhost
      port: 6379
      password: wisenut1!
      timeout: 2000ms

logging:
  level:
    root: info
  file:
    name: logs/gateway.log

server:
  port: 8080

agent:
  url: http://localhost:8000/chat