spring.application.name=mcp-server

server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/data_info
spring.datasource.name=wisenut
spring.datasource.username=wisenut
spring.datasource.password=wisenut1!
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.dbcp2.driver-class-name=spring.datasource.driver-class-name=org.postgresql.Driver

mybatis.mapper-locations=classpath:mappers/**/*Mapper.xml
mybatis.type-aliases-package=com.aiagent.mcpserver.model
mybatis.configuration.map-underscore-to-camel-case=true